### ISSUE TITLE
Symfony3 support

### ISSUE THREAD

**Issue by robertfausk** [QafooLabs/QafooLabsNoFrameworkBundle#19]
Actually this bundle prevents users from upgrade to symfony 3. At least if they are using the FormRequest because the used ```Form::isBound()``` was removed.

@UFOMelkor created a PR for this two months ago https://github.com/QafooLabs/QafooLabsNoFrameworkBundle/pull/18

**Comment by pdoreau** [comment]
:+1: 
would be nice to allow symfony3 upgrade

**Comment by beberlei** [comment]
#18 was merged
